name: Build on Push to Build Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # Permissions to use OIDC token authentication
    permissions:
      contents: read
      id-token: write
      # Allows pushing to the GitHub Container Registry
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Depot
        uses: depot/setup-action@v1
      
      - name: Build and push Docker image
        uses: depot/build-push-action@v1
        with:
          project: wf2rwqhlzs
          context: .
          push: true
          tags: |
            fajyz/flux-app-training-serverless-worker:${{ github.sha }}
          platforms: linux/amd64

